workflows:
  flutter-monorepo-workflow:
    name: Flutter App Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    working_directory: mobile/src
    
    environment:
      groups:
        - gitcrypt_vars
    
    triggering:
      events:
        - push
        - pull_request
      cancel_previous_builds: true
      
    when:
      changeset:
        includes:
          - 'mobile/src/**'
            
    scripts:
      - name: Unlock git-crypt
        script: |
          set -e
          
          # Install git-crypt on the macOS build machine
          brew install git-crypt
          
          # Decode the base64 environment variable back into a binary key file
          echo $GIT_CRYPT_KEY | base64 --decode > /tmp/git-crypt-key.key
          
          # Navigate to the correct root of the repository to unlock it
          cd $CM_BUILD_DIR
          git-crypt unlock /tmp/git-crypt-key.key
          
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Build iOS IPA
        script: flutter build ipa --release        
        
    artifacts:
      - build/ios/ipa/*.ipa