workflows:
  flutter-monorepo-workflow:
    name: Flutter App Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    working_directory: mobile/src
    
    triggering:
      events:
        - push
        - pull_request
      cancel_previous_builds: true
      
    # CORRECT PLACEMENT: 'when' is a sibling to 'triggering', not a child of it!
    when:
      changeset:
        includes:
          - 'mobile/src/**'
            
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android App Bundle
        script: flutter build appbundle --release
        
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk