<#import "template.ftl" as layout>

<@layout.registrationLayout displayMessage=true displayInfo=false; section>
  <#if section = "header">
    ${msg("auth-totp-header")}
  <#elseif section = "form">
    <div class="cfi-form">
      
      <#-- Mobile Brand Block -->
      <div class="cfi-brand">
        <div class="cfi-logo">
          <img class="cfi-logo-img" src="${url.resourcesPath}/img/cfi-logo.png" alt="CFI-CARE" />
        </div>
        <h2 class="cfi-title">CFI-CARE</h2>
        <p class="cfi-subtitle">Your Health, Our Priority</p>
      </div>

      <div class="cfi-tabs cfi-tabs-single">
        <span class="cfi-tab active">Verify Identity</span>
      </div>

      <#-- Error Message Block -->
      <#if message?has_content>
        <div class="cfi-inline-message cfi-inline-${(message.type!'info')?lower_case}" role="alert" style="font-size: 36px; padding: 24px; margin-bottom: 24px; text-align: center; border-radius: 16px; font-weight: 600;">
          ${kcSanitize(message.summary)?no_esc}
        </div>
      </#if>

      <#-- Context Card Layout -->
      <div class="cfi-otp-item" style="width: 100%; display: flex; flex-direction: column; align-items: center; justify-content: center; box-sizing: border-box; min-height: 180px; padding: 32px 24px; text-align: center; margin-bottom: 24px; border: 1px solid var(--cfi-border); background: #ffffff;">
        <span style="display: block; width: 64px; height: 64px; margin-bottom: 16px; background-image: url('data:image/svg+xml;utf8,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%2216%22 height=%2216%22 fill=%22%231e88e5%22 class=%22bi bi-phone%22 viewBox=%220 0 16 16%22><path d=%22M11 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM5 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z%22/><path d=%22M8 14a1 1 0 1 0 0-2 1 1 0 0 0 0 2%22/></svg>'); background-size: contain; background-repeat: no-repeat; background-position: center;"></span>
        <div style="font-weight: 700; color: var(--cfi-text); font-size: 40px; margin-bottom: 12px; width: 100%;">Authenticator App</div>
        <div style="color: var(--cfi-muted); font-size: 40px; font-weight: 400; line-height: 1.45; text-align: center; width: 100%;">Enter the verification code generated by your device app.</div>
      </div>

      <#-- Updated Form Action with correct input tracking names -->
      <form id="kc-totp-login-form" action="${url.loginAction}" method="post">
        <div class="form-group" style="margin-bottom: 24px;">
          <label for="otp" style="display: block; text-align: left; font-size: 40px; font-weight: 700; color: var(--cfi-text); margin-bottom: 12px;">
            <#assign rawLabel = msg("loginTotpOneTime")>
            <#if rawLabel?contains("loginTotpOneTime")>Verification Code<#else>${rawLabel}</#if>
          </label>
          <#-- Enforced name="otp" field assignment here -->
          <input tabindex="1" id="otp" name="otp" class="form-control" 
                 type="text" autocomplete="one-time-code" inputmode="numeric" autofocus dir="ltr" />
        </div>

        <div class="cfi-form-actions" style="margin-top: 28px;">
          <input tabindex="2" class="btn btn-primary" name="login" id="kc-login" type="submit" value="${msg("doLogIn")}" />
        </div>
      </form>

      <div class="cfi-help" >
        <a href="${url.loginRestartFlowUrl}">Back to Login</a>
        
        <form action="${url.loginAction}" method="post"
              style="display: inline; margin: 0; padding: 0;">
              <input type="hidden" name="recoveryCodeInput" value="" />
              <button type="submit" name="tryAnotherWay" value="on" class="cfi-help"
                  style="background: none !important; border: none !important; padding: 0 !important; cursor: pointer; font-family: inherit;">
                  <a>Try Another Way </i></a>
              </button>
          </form>
      </div>

    </div>
  </#if>
</@layout.registrationLayout>