<#import "template.ftl" as layout>
<#-- Changed displayInfo to true so Keycloak populates the native identity/reset links -->
<@layout.registrationLayout displayMessage=false displayInfo=true; section>
  <#if section = "header">
  <#elseif section = "form">
    <div class="cfi-shell">
      <div class="cfi-hero">
        <div class="cfi-brand">
          <div class="cfi-brand-mark" aria-hidden="true">
            <i class="bi bi-activity"></i>
          </div>
          <div class="cfi-brand-copy">
            <h1>CFI-Care</h1>
            <p>AI-Powered Collaborative Health Records</p>
          </div>
        </div>

        <div class="cfi-feature-list" role="list">
          <div class="cfi-feature" role="listitem">
            <div class="cfi-feature-icon" aria-hidden="true"><i class="bi bi-shield"></i></div>
            <div class="cfi-feature-copy">
              <h3>Extra Verification</h3>
              <p>A short second step keeps the account access flow secure.</p>
            </div>
          </div>

          <div class="cfi-feature" role="listitem">
            <div class="cfi-feature-icon" aria-hidden="true"><i class="bi bi-phone"></i></div>
            <div class="cfi-feature-copy">
              <h3>Authenticator Code</h3>
              <p>Use the OTP generated by your device or backup credential.</p>
            </div>
          </div>
        </div>
      </div>

      <div class="cfi-panel">
        <div class="cfi-card" role="region" aria-labelledby="cfi-card-title">
          <div class="cfi-card-head">
            <div>
              <h2 id="cfi-card-title">Input OTP Code</h2>
              <p>Enter the six-digit code to continue</p>
            </div>
          </div>

          <#if message?has_content>
            <div class="cfi-inline-message cfi-inline-${(message.type!'info')?lower_case}" role="alert" aria-live="polite">
              ${kcSanitize(message.summary)?no_esc}
            </div>
          </#if>

          <form id="kc-otp-login-form" action="${url.loginAction}" method="post" class="cfi-form" onsubmit="login.disabled = true; return true;" novalidate>
            <#if otpLogin.userOtpCredentials?size gt 1>
              <div class="form-group" style="margin-bottom: 2rem;">
                <label style="display: block; margin-bottom: 12px; font-weight: 500; font-size: 15px; color: var(--cfi-muted);">${msg("loginChooseAuthenticator")}</label>
                <div style="display: grid; gap: 12px;">
                  <#list otpLogin.userOtpCredentials as otpCredential>
                    <label style="display: flex; align-items: center; gap: 12px; padding: 16px; border: 1px solid rgba(255,255,255,0.15); border-radius: 12px; background: rgba(255,255,255,0.06); color: #fff; font-weight: 500; font-size: 15px; cursor: pointer; transition: background 0.2s ease;">
                      <input id="kc-otp-credential-${otpCredential?index}"
                             type="radio"
                             name="selectedCredentialId"
                             value="${otpCredential.id}"
                             style="accent-color: #06b6d4; width: 18px; height: 18px; margin: 0;"
                             <#if otpCredential.id == otpLogin.selectedCredentialId>checked="checked"</#if> />
                      <span>${otpCredential.userLabel}</span>
                    </label>
                  </#list>
                </div>
              </div>
            </#if>

            <div class="form-group cfi-floating-group" style="margin-bottom: 2rem;">
              <input id="otp"
                     name="otp"
                     type="text"
                     class="form-control"
                     placeholder=" "
                     autocomplete="one-time-code"
                     inputmode="numeric"
                     autofocus
                     aria-invalid="<#if messagesPerField.existsError('totp')>true</#if>"
                     dir="ltr" />
              <label for="otp" class="cfi-floating-label">${msg("loginOtpOneTime")}</label>
            </div>

            <button class="cfi-submit" name="login" id="kc-login" type="submit">${msg("doLogIn")}</button>
          </form>

          <div class="cfi-help"
                style="margin-top: 1.5rem; display: flex; justify-content: space-between; align-items: center;">
                <#assign hostUrl=url.resourcesCommonPath?keep_before("/keycloak")>

                    <a href="${hostUrl}/login"> <i class="bi bi-arrow-left-short"></i> Back to Login</a>


                    <form action="${url.loginAction}" method="post" id="kc-select-back-form"
                        style="display: inline; margin: 0; padding: 0;">
                        <#-- Satisfies the recovery authenticator's backend check to prevent
                            NullPointerException -->
                            <input type="hidden" name="recoveryCodeInput" value="" />

                            <button type="submit" name="tryAnotherWay" value="on"
                                class="cfi-link-button"
                                style="background: none; border: none; padding: 0; margin: 0; font-weight: 600; color:rgba(255,255,255,0.7); font-size: 1rem; cursor: pointer;">
                                Try Another Way <i class="bi bi-arrow-right-short"></i>
                            </button>
                    </form>
            </div>
        </div>
      </div>
    </div>

    <script>
      (function () {
        var mount = document.getElementById('cfi-otp-identity-helper');
        if (!mount) return;

        // Extracting elements if provided by base theme context structures
        var attemptedUsername = document.getElementById('kc-attempted-username') || document.getElementById('kc-username');
        
        if (attemptedUsername) {
          attemptedUsername.style.display = 'block';
          attemptedUsername.style.marginBottom = '4px';
          attemptedUsername.style.color = 'rgba(255, 255, 255, 0.5)';
          mount.appendChild(attemptedUsername);
        }
      })();
    </script>
  </#if>
</@layout.registrationLayout>