parent=base
import=common/keycloak
styles=css/cfi-auth.css

kcHtmlTitle=CFI-Care

cfiShowRegisterTab=true
cfiHideRegisterOnKcAction=true
cfiHideTabsOnKcAction=true
cfiLockUsernameOnKcAction=true
cfiShowFeaturePanel=true
themeCacheEnabled=false
themeResourceCacheEnabled=false

scripts=js/altcha-import.js