import 'package:flutter/material.dart';
 import '../utils/schedule_utils.dart';


class Document {
  final String? id; // Added ID for Database
  final String title;
  final String filePath;
  final bool isPDF;
  
  final String summary;
  final String details;
  final TypeOfEventEnum type;
  final SpecialityEventEnum speciality;
  final TimeOfDay time;

  Document({
    this.id, // Optional, generated by DB/App
    required this.title,
    required this.filePath,
    required this.isPDF,
    this.summary = '',
    this.details = '',
    this.type = TypeOfEventEnum.other,
    this.speciality = SpecialityEventEnum.other,
    this.time = const TimeOfDay(hour: 0, minute: 0),
  });
}