// Mocks generated by Mockito 5.4.6 from annotations
// in medflow/test/unit_tests/access_grant_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:medflow/data/services/datasources/api_service_booking.dart'
    as _i3;
import 'package:medflow/domain/models/grant_model.dart' as _i5;
import 'package:medflow/domain/repository/access_grant_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiService_0 extends _i1.SmartFake implements _i3.ApiService {
  _FakeApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOtpResponse_0 extends _i1.SmartFake implements _i5.OtpResponse {
  _FakeOtpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccessGrantRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccessGrantRepository extends _i1.Mock
    implements _i2.AccessGrantRepository {
  MockAccessGrantRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i3.ApiService);

  @override
  _i4.Future<_i5.OtpResponse> requestOtp() => (super.noSuchMethod(
        Invocation.method(#requestOtp, []),
        returnValue: _i4.Future<_i5.OtpResponse>.value(
          _FakeOtpResponse_0(
            this,
            Invocation.method(#requestOtp, []),
          ),
        ),
      ) as _i4.Future<_i5.OtpResponse>);

  @override
  _i4.Future<List<_i5.PendingGrant>> getPendingGrants() => (super.noSuchMethod(
        Invocation.method(#getPendingGrants, []),
        returnValue:
            _i4.Future<List<_i5.PendingGrant>>.value(<_i5.PendingGrant>[]),
      ) as _i4.Future<List<_i5.PendingGrant>>);

  @override
  _i4.Future<_i5.Grant?> respondToGrant({
    required String? handshakeId,
    required bool? approved,
    int? durationMinutes = 60,
    List<String>? scopes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #respondToGrant,
          [],
          {
            #handshakeId: handshakeId,
            #approved: approved,
            #durationMinutes: durationMinutes,
            #scopes: scopes,
          },
        ),
        returnValue: _i4.Future<_i5.Grant?>.value(),
      ) as _i4.Future<_i5.Grant?>);

  @override
  _i4.Future<void> revokeGrant(String? practitionerId) => (super.noSuchMethod(
        Invocation.method(#revokeGrant, [practitionerId]),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Grant>> getActiveGrants() => (super.noSuchMethod(
        Invocation.method(#getActiveGrants, []),
        returnValue: _i4.Future<List<_i5.Grant>>.value(<_i5.Grant>[]),
      ) as _i4.Future<List<_i5.Grant>>);

  @override
  _i4.Future<String?> fetchPractitionerName(String? practitionerId) =>
      (super.noSuchMethod(
        Invocation.method(#fetchPractitionerName, [practitionerId]),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}
