// Mocks generated by Mockito 5.4.6 from annotations
// in medflow/test/unit_tests/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:medflow/domain/models/auth_model.dart' as _i3;
import 'package:medflow/domain/repository/auth_repo.dart' as _i5;
import 'package:medflow/domain/usecases/auth_usecases.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthModel_0 extends _i1.SmartFake implements _i3.AuthModel {
  _FakeAuthModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthenticationRepository_0 extends _i1.SmartFake
    implements _i5.AuthenticationRepository {
  _FakeAuthenticationRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthUsecases].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthUsecases extends _i1.Mock implements _i2.AuthUsecases {
  MockAuthUsecases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.AuthenticationRepository get repo => (super.noSuchMethod(
        Invocation.getter(#repo),
        returnValue: _FakeAuthenticationRepository_0(
          this,
          Invocation.getter(#repo),
        ),
      ) as _i5.AuthenticationRepository);

  @override
  _i4.Future<_i3.AuthModel> login() => (super.noSuchMethod(
        Invocation.method(#login, []),
        returnValue: _i4.Future<_i3.AuthModel>.value(
          _FakeAuthModel_0(
            this,
            Invocation.method(#login, []),
          ),
        ),
      ) as _i4.Future<_i3.AuthModel>);

  @override
  _i4.Future<_i3.AuthModel?> restoreSession() => (super.noSuchMethod(
        Invocation.method(#restoreSession, []),
        returnValue: _i4.Future<_i3.AuthModel?>.value(),
      ) as _i4.Future<_i3.AuthModel?>);

  @override
  _i4.Future<_i3.AuthModel> refreshSession() => (super.noSuchMethod(
        Invocation.method(#refreshSession, []),
        returnValue: _i4.Future<_i3.AuthModel>.value(
          _FakeAuthModel_0(
            this,
            Invocation.method(#refreshSession, []),
          ),
        ),
      ) as _i4.Future<_i3.AuthModel>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(#logout, []),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getValidAccessToken() => (super.noSuchMethod(
        Invocation.method(#getValidAccessToken, []),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<_i3.AuthModel> runKeycloakAction(String? action) =>
      (super.noSuchMethod(
        Invocation.method(#runKeycloakAction, [action]),
        returnValue: _i4.Future<_i3.AuthModel>.value(
          _FakeAuthModel_0(
            this,
            Invocation.method(#runKeycloakAction, [action]),
          ),
        ),
      ) as _i4.Future<_i3.AuthModel>);

  @override
  _i4.Future<_i3.AuthModel> updatePassword() => (super.noSuchMethod(
        Invocation.method(#updatePassword, []),
        returnValue: _i4.Future<_i3.AuthModel>.value(
          _FakeAuthModel_0(
            this,
            Invocation.method(#updatePassword, []),
          ),
        ),
      ) as _i4.Future<_i3.AuthModel>);
}

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i1.Mock
    implements _i5.AuthenticationRepository {
  MockAuthenticationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.AuthModel> login() => (super.noSuchMethod(
        Invocation.method(#login, []),
        returnValue: _i4.Future<_i3.AuthModel>.value(
          _FakeAuthModel_0(
            this,
            Invocation.method(#login, []),
          ),
        ),
      ) as _i4.Future<_i3.AuthModel>);

  @override
  _i4.Future<_i3.AuthModel?> restoreSession() => (super.noSuchMethod(
        Invocation.method(#restoreSession, []),
        returnValue: _i4.Future<_i3.AuthModel?>.value(),
      ) as _i4.Future<_i3.AuthModel?>);

  @override
  _i4.Future<_i3.AuthModel> refreshSession() => (super.noSuchMethod(
        Invocation.method(#refreshSession, []),
        returnValue: _i4.Future<_i3.AuthModel>.value(
          _FakeAuthModel_0(
            this,
            Invocation.method(#refreshSession, []),
          ),
        ),
      ) as _i4.Future<_i3.AuthModel>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(#logout, []),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getValidAccessToken() => (super.noSuchMethod(
        Invocation.method(#getValidAccessToken, []),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<_i3.AuthModel> runKeycloakAction(String? action) =>
      (super.noSuchMethod(
        Invocation.method(#runKeycloakAction, [action]),
        returnValue: _i4.Future<_i3.AuthModel>.value(
          _FakeAuthModel_0(
            this,
            Invocation.method(#runKeycloakAction, [action]),
          ),
        ),
      ) as _i4.Future<_i3.AuthModel>);

  @override
  _i4.Future<_i3.AuthModel> updatePassword() => (super.noSuchMethod(
        Invocation.method(#updatePassword, []),
        returnValue: _i4.Future<_i3.AuthModel>.value(
          _FakeAuthModel_0(
            this,
            Invocation.method(#updatePassword, []),
          ),
        ),
      ) as _i4.Future<_i3.AuthModel>);
}
