// Mocks generated by Mockito 5.4.6 from annotations
// in medflow/test/unit_tests/patient_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:medflow/data/services/datasources/api_service_booking.dart'
    as _i4;
import 'package:medflow/domain/repository/patient_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiService_0 extends _i1.SmartFake implements _i4.ApiService {
  _FakeApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PatientRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPatientRepository extends _i1.Mock implements _i2.PatientRepository {
  MockPatientRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i4.ApiService);

  @override
  _i3.Future<_i2.PatientProfile?> fetchPatient(String? patientId) =>
      (super.noSuchMethod(
        Invocation.method(#fetchPatient, [patientId]),
        returnValue: _i3.Future<_i2.PatientProfile?>.value(),
      ) as _i3.Future<_i2.PatientProfile?>);

  @override
  _i3.Future<void> updatePatient(_i2.PatientProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(#updatePatient, [profile]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
