services:
  vault:
    image: hashicorp/vault:1.21.2
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./services/hashicorp/config:/vault/config:ro
      - ./services/hashicorp/data:/vault/file
      - ./vault-policies/:/vault/policies
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    command: "vault server -config=/vault/config/${VAULT_CONFIG_FILE:-vault-config.generated.json}"
    networks:
      - nginx-network


networks:
  nginx-network:
    driver: bridge