services:
  backend:
    container_name: nodejs
    build:
      context: ./
      dockerfile: Dockerfile
    image: cfi-backend
    env_file:
      - ./.env
    restart: unless-stopped
    
    # depends_on:
    #   redis:
    #     condition: service_healthy
    networks:
      - nginx-network

    volumes:
    
    - ../../../security/Containers/static:/security/Containers/static:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'


networks:
  nginx-network:
      
    name: containers_nginx-network
    external: true