
# FROM postgres:18.0-alpine

FROM postgres@sha256:0ce0d1fa5bf54b7b338e09829ab76b479dbd0702da50bf0cdf5c258208e47f40


# https://hub.docker.com/_/postgres
# 70 is the standard uid/gid for "postgres" in Alpine as per the postgres:17.2-alpine Docker file:
# https://github.com/docker-library/postgres/blob/b23470265cc9c4bc283a88bf6c5054e3fca87c16/17/alpine3.21/Dockerfile
