@startuml
actor User
participant Browser
participant Keycloak
participant nginx
participant NodeJS
participant FHIR

User -> Browser : Login request
Browser -> Keycloak : Authentication request
Keycloak -> Browser: Access token for Authorization


User -> Browser : Action that needs Data
Browser -> nginx : API call
nginx -> NodeJS : request
NodeJS -> NodeJS : validate JWT
NodeJS -> NodeJS : enforce resource checks
NodeJS -> FHIR : forward Authorization
FHIR -> NodeJS : resource
NodeJS -> nginx : response
nginx -> Browser : response
Browser -> User : display data
@enduml
