// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKjdasfJYvlgwu44V897Kq82xIrO5-MUA',
    appId: '1:236089077569:web:d6622e105518b725b97bc0',
    messagingSenderId: '236089077569',
    projectId: 'notifications-medflow',
    authDomain: 'notifications-medflow.firebaseapp.com',
    storageBucket: 'notifications-medflow.firebasestorage.app',
    measurementId: 'G-JKBKMS23VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcSkV_Ru3S_gWNdP-95J8gNcCdnfLPgPM',
    appId: '1:236089077569:android:f274a1256f66d13bb97bc0',
    messagingSenderId: '236089077569',
    projectId: 'notifications-medflow',
    storageBucket: 'notifications-medflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvz_OF3r0O9Lwlvx6BLPisLHguUI9FBYc',
    appId: '1:236089077569:ios:bfa4f669e36700deb97bc0',
    messagingSenderId: '236089077569',
    projectId: 'notifications-medflow',
    storageBucket: 'notifications-medflow.firebasestorage.app',
    iosBundleId: 'com.example.medflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvz_OF3r0O9Lwlvx6BLPisLHguUI9FBYc',
    appId: '1:236089077569:ios:bfa4f669e36700deb97bc0',
    messagingSenderId: '236089077569',
    projectId: 'notifications-medflow',
    storageBucket: 'notifications-medflow.firebasestorage.app',
    iosBundleId: 'com.example.medflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKjdasfJYvlgwu44V897Kq82xIrO5-MUA',
    appId: '1:236089077569:web:9e409a10e3ef74e7b97bc0',
    messagingSenderId: '236089077569',
    projectId: 'notifications-medflow',
    authDomain: 'notifications-medflow.firebaseapp.com',
    storageBucket: 'notifications-medflow.firebasestorage.app',
    measurementId: 'G-C0PS7HWCXG',
  );
}
